### ISSUE TITLE
Error when uploading with `Transfer-Encoding: chunked` 

### ISSUE THREAD

**Issue by bilogic** [kd2org/picodav#6]
```
PUT /webdav.php/ebook.epub HTTP/1.1
Host: bookfirst.dv1.e115.com
Authorization: Basic YWRtaW46ZmpnaDQ0Mw==
TE: trailers
Transfer-Encoding: chunked
Connection: close, TE
User-Agent: KOReader/2023.01 (https://koreader.rocks/) LuaSocket/3.0.0

800
PK..........!.oa.,............mimetypeapplication/epub+zipPK.........s;T.
...(..AK......ops/f000c-02.jpg.zu\S.....6z....n...QCZ@...I..!!
.....*".. ...RPAAA.CD..S%....|......y../8.\u_u...}.s..I...3..	....S..@.e.3..y...% 	..-.....2.".. ..J......'~.$.].L>.S......)..O...4.....V.a...^.=..X........."Ue..
...5......
```

I captured the above with tcpdump. it resulted in `ebook.pub` being a 0 byte file on the server. Any idea? Thank you.

**Comment by bohwaz** [comment]
Thanks for the report. This might be a web server issue as documented here : https://sabre.io/dav/0bytes/

What webserver and version are you using?

**Comment by bilogic** [comment]
It's Apache/2.4.52 on ubuntu with PHP-FPM

**Comment by bohwaz** [comment]
Mod_php or fpm?

**Comment by bilogic** [comment]
FPM

**Comment by bohwaz** [comment]
Ah sorry yeah didn't see that you mentioned it first.

I just tested with FPM and it is definitely a bug in Apache mod_fcgid, as reported here: 
- https://github.com/nextcloud/server/issues/7995
- https://www.jeffgeerling.com/blog/2017/apache-fastcgi-proxyfcgi-and-empty-post-bodies-chunked-transfer
- https://docs.cyberduck.io/mountainduck/issues/fastcgi/
- https://evertpot.com/260/

This has been fixed in 2018, in mod_fcgid 2.3.10:
- https://bz.apache.org/bugzilla/show_bug.cgi?id=53332
- https://svn.apache.org/viewvc/httpd/mod_fcgid/trunk/CHANGES-FCGID?view=markup

Unfortunately Debian and Ubuntu are stuck with mod_fcgid: https://tracker.debian.org/pkg/libapache2-mod-fcgid

You can try in CLI like that:

```
curl -v http://picodav.localhost/test.mp4 -u bohwaz:abcd -T /home/bohwaz/test.mp4 --header "Transfer-Encoding: chunked"
```

You should either compile your own mod_fcgid or switch over to mod_php. I'll add an error message for FPM when chunked transfer encoding is used.

**Comment by bohwaz** [comment]
Thank your for your report, a new error message is generated if this issue is detected, so that zero-length files won't be created.

I contacted the Debian package maintainer and offered a bounty to upload the new mod_fcgid version, so hopefully Debian will get this fixed in next release or even in backports.

**Comment by bilogic** [comment]
Wow, thank you so much! The error report alone is great!
